version: 2.1

orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.4

jobs:
  heroku-deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
#       - run: heroku container:login
      - run: heroku container:push -a $HEROKU_APP_NAME web
      - run: heroku container:release -a $HEROKU_APP_NAME web 

workflows:
  test-build-deploy:
    jobs:
      - node/test
      - heroku-deploy:
          requires:
            - node/test
          filters:
            branches:
              only: 
                - main
